#!/bin/sh
### BEGIN INIT INFO
# Provides:             es-river-mongodb
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    es-river-mongodb - Indexes MongoDB to Elasticsearch
# Description:          es-river-mongodb - Indexes MongoDB to Elasticsearch
### END INIT INFO

DAEMON=/usr/local/bin/es-river-mongodb
RUNDIR=/run/es-river-mongodb
PIDFILE=$RUNDIR/es-river-mongodb.pid
CONFIGFILE=/etc/es-river-mongodb/config.cfg
ARGS="-d -c=$CONFIGFILE -pid=$PIDFILE"
NAME="es-river-mongodb"

test -x $DAEMON || exit 0

case "$1" in
    start)
        if start-stop-daemon --start --quiet --chuid es-river-mongodb:es-river-mongodb --exec $DAEMON -- $ARGS
        then
            echo "$NAME started."
        else
            echo "$NAME starting failed."
        fi
        ;;
    stop)
        if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
        then
            echo "$NAME stopped."
        else
            echo "$NAME stop failed"
        fi
        rm -f $PIDFILE
        sleep 1
        ;;
    restart)
        ${0} stop
        ${0} start
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
