#!/bin/sh
set -e

case "$1" in
  install)
    adduser --system --no-create-home --group es-river-mongodb
    mkdir -p /run/es-river-mongodb
    chown -R es-river-mongodb: /run/es-river-mongodb
    ;;

  upgrade)
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
